[package]
name = "dl"
version = "0.1.0"
edition = "2021"



[dependencies]
hyper = { version = "*", features = ["full"] }
hyper-tls = "*"
tokio = { version = "*", features = ["full"] }
file_diff = "*"